set -g default-terminal "tmux-256color"
set -sa terminal-overrides ",xterm*:Tc,alacritty:Tc,tmux-256color:Tc"
set -s escape-time 0
set -g history-limit 100000
set -g display-time 3000
set -g status-interval 5
set -g focus-events on
set -g set-clipboard on
set -g base-index 1
set -g renumber-windows on
set -g detach-on-destroy off
set -g mouse on
setw -g pane-base-index 1
setw -g aggressive-resize on
set -g prefix M-b
unbind C-b
bind M-b send-prefix
bind r source-file ~/.tmux.conf \; display "Config reloaded!"
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"
unbind '"'
unbind %
bind c new-window -c "#{pane_current_path}"
bind-key -n M-n next-window
bind-key -n M-p previous-window
bind g run "~/.local/dots/scripts/open-github.sh"
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R
bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5
bind -n M-1 select-window -t 1
bind -n M-2 select-window -t 2
bind -n M-3 select-window -t 3
bind -n M-4 select-window -t 4
bind -n M-5 select-window -t 5
bind -n M-6 select-window -t 6
bind -n M-7 select-window -t 7
bind -n M-8 select-window -t 8
bind -n M-9 select-window -t 9
bind Tab last-window
bind -r < swap-window -d -t -1
bind -r > swap-window -d -t +1
bind S choose-tree -Zs
bind x kill-pane
bind X kill-window
bind f run "tmux neww ~/.local/dots/scripts/tmux.sh"
setw -g mode-keys vi
set -g status-keys emacs
set -g status-position top
set -g status-style "bg=#191724,fg=#6e6a86"
setw -g window-status-format "#[fg=#403d52] #W "
setw -g window-status-current-format "#[fg=#9ece6a] #W "
setw -g window-status-separator "|"
set -g status-justify centre
set -g status-left-length 50
set -g status-right-length 50
set -g status-left "#[fg=#26233a]#{?client_prefix,#[fg=#ebbcba],} "
set -g status-right ""
set -g status-justify centre
setw -g window-status-separator " "
setw -g window-status-format "#[fg=#403d52,bg=default]  #W  "
setw -g window-status-current-format "#[fg=#9ece6a,bold]  #W  "
setw -g window-status-activity-style "fg=#e0af68,bold"
setw -g window-status-bell-style "fg=#f7768e,bold"
set -g pane-border-style "fg=#313244"
set -g pane-active-border-style "fg=#9ece6a"
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-yank'
if "test ! -d ~/.tmux/plugins/tpm" \
   "run 'git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm && ~/.tmux/plugins/tpm/bin/install_plugins'"
run '~/.tmux/plugins/tpm/tpm'
