-- local lspconfig=require('lspconfig')
--
-- local on_attach=function(client,bufnr)
--   local keymap=vim.keymap.set
--   local opts={
--     noremap=true,
--     siletn=true,
--     buffer=bufnr,
--   }
--
--   --native neovim keymaps
--
--   keymap("n","<leader>gD","<cmd>lua vim.lsp.buf.definition()<CR>",opts) -- goto definition
--   keymap("n","<leader>gs","<cmd>vsplit | lua vim.lsp.buf.definition()<CR>",opts) -- goto definition in split
--   keymap("n","<leader>ca","<cmd>lua vim.lsp.buf.code_action()<CR>",opts) -- code action 
--   keymap("n","<leader>rn","<cmd>lua vim.lsp.buf.rename()<CR>",opts) --  rename symbol
--
--
--   keymap("n","<leader>gd","<cmd>Fzflua lsp_finder<CR>",opts) -- goto definition
-- end
-- lspconfig.lua_ls.setup({
--   on_attach=on_attach,
--   settings={
--     Lua={
--       diagnostics={
--         globals={"vim"},
--       },
--       workspace={
--         library={
--           vim.fn.expand("$VIMRUNTIME/lua"),
--           vim.fn.expand("$XDG_CONFIG_HOME") .. "/nvim/lua",
--         }
--       }
--     }
--   }
-- })
