require("mini.pairs").setup()
require("mini.surround").setup()
require("mini.misc").setup()
require("mini.extra").setup()
require("mini.notify").setup()
require("mini.git").setup()
require("mini.tabline").setup()
-- require("mini.cursorword").setup()
require("mini.indentscope").setup()
