[main]
font=JetBrainsMono Nerd Font:size=16
pad=10x10

[cursor]
style=beam
blink=yes
blink-rate=500
unfocused-style=hollow

[colors-dark]
background=303446
urls=e78284
foreground=c6d0f5
selection-foreground=c6d0f5
selection-background=51576d
# Normal colors (0-7)
regular0=232634
regular1=e78284
regular2=a6d189
regular3=e5c890
regular4=8caaee
regular5=ca9ee6
regular6=99d1db
regular7=b5bfe2
# Bright colors (8-15)
bright0=626880
bright1=e78284
bright2=a6d189
bright3=e5c890
bright4=8caaee
bright5=ca9ee6
bright6=99d1db
bright7=c6d0f5

[scrollback]
lines=10000
multiplier=3

[key-bindings]
clipboard-paste=Control+Shift+v

font-increase=Mod1+Shift+j
font-decrease=Mod1+Shift+k
font-reset=Control+0

scrollback-up-page=Shift+Page_Up
scrollback-down-page=Shift+Page_Down
scrollback-home=Shift+Home
scrollback-end=Shift+End

spawn-terminal=Control+Shift+n


[url]
launch=xdg-open ${url}
osc8-underline=always
